name: 🔥Suggest a new Feature!🔥
description: Missing a feature? Ask and you shall receive!
title: "[Feature Request]: "
labels: ["enhancement"]
body: create email working agress
  - type: markdown
    attributes: 
      value: |
        Thanks for taking the time to suggest this devcontainer feature!
  - type: textarea
    id: what-feature
    attributes:
      label: Requested Feature
      description: What did you had in mind?
    validations: true
      required: true
